services:
    strapi:
        container_name: strapi
        build: ./admin
        restart: unless-stopped
        env_file: .env
        environment:
            - DATABASE_CLIENT=postgres
            - DATABASE_HOST=postgres-server
            - DATABASE_PORT=5432
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
            - JWT_SECRET=${JWT_SECRET}
            - APP_KEYS=${APP_KEYS}
            - NODE_ENV=${NODE_ENV}
            - API_TOKEN_SALT=${API_TOKEN_SALT}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_USERNAME=${ADMIN_USERNAME}
        ports:
            - "1337:1337"
        networks:
            - shared

    next:
        container_name: next
        build: ./frontend
        restart: unless-stopped
        environment:
            - NODE_ENV=${NODE_ENV}
            - API_URL=${API_URL}
        ports:
            - "3000:3000"
        networks:
            - shared

networks:
    shared:
        external: true